<<<<<<< HEAD
<!-- Generated by ::xowiki::ADP_Generator on Fri Mar 10 12:32:17 BRT 2017 -->
=======
<!-- Generated by ::xowiki::ADP_Generator on Tue Mar 07 16:50:12 UTC 2017 -->
>>>>>>> 1c25353865b4f810e20e44ec5e5b28b4518efa5d
<!-- The following DIV is needed for overlib to function! -->
          <div id="overDiv" style="position:absolute; visibility:hidden; z-index:1000;"></div>    
          <div class='xowiki-content'>

 @top_includelets;noquote@
 <if @body.menubarHTML@ not nil><div class='visual-clear'><!-- --></div>@body.menubarHTML;noquote@</if>
 <if @page_context@ not nil><h1>@body.title@ (@page_context@)</h1></if>
 <else><h1>@body.title@</h1></else>
 <if @folderhtml@ not nil> 
 <div class='folders' style=''>@folderhtml;noquote@</div> 
 <div class='content-with-folders'>@content;noquote@</div> 
 </if>
    <else>@content;noquote@</else>

</div> <!-- class='xowiki-content' -->
